version: '2'
services:
  web:
    build:  
      context: .
      dockerfile: Dockerfile 
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "80:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}

